# .github/actions/colcon-build-action/action.yml
name: 'ROS2 Colcon Build Action'
description: 'Build ROS2 workspace with colcon inside Docker container'
inputs:
  command:  # Input parameter to pass a command
    description: 'Command to run in the Docker container'
    required: true
    default: 'colcon build'  # Default command for building ROS 2 packages
outputs:
  build-status:  # Output to indicate success or failure
    description: 'The status of the build'

runs:
  using: 'docker'
  image: 'Dockerfile'  # Path to your Dockerfile inside this folder
  args:
    - bash -c "source /opt/ros/humble/setup.bash && \
               mkdir -p /workspace/src && \
               cp -r /github/workspace/src/* /workspace/src/ && \
               source /workspace/install/setup.bash && \
               colcon build"
