name: Build and Run colcon in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (optional for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build Docker image if it doesn't already exist
      - name: Build Docker image if it doesn't exist
        run: |
          if ! docker image inspect myimage:latest > /dev/null 2>&1; then
            docker build -t myimage:latest -f ./Dockerfile .
          fi

      # Run Docker container from the pre-built image
      - name: Run Docker container from the image
        run: |
          docker run -d --name test-container --memory="4g" --cpus="2" myimage:latest

      # Set up ROS 2 environment in Docker container and run colcon build
      - name: Set up ROS 2 environment in Docker container and run colcon build
        run: |
          docker exec test-container bash -c "source /opt/ros/humble/setup.bash && \
          source ~/ros_ws/install/setup.bash && \
          colcon build"

      # Show colcon build result
      - name: Show colcon build result
        run: |
          docker exec test-container bash -c "source /opt/ros/humble/setup.bash && \
          source ~/ros_ws/install/setup.bash && \
          colcon build && \
          tail -n 20 ~/ros_ws/log/latest_build/colcon_build_output.log"

      # Stop and remove Docker container after the build
      - name: Clean up Docker container
        run: |
          docker stop test-container
          docker rm test-container
