name: Build and Run colcon in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (optional for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build Docker image if it doesn't already exist
      - name: Build Docker image if it doesn't exist
        run: |
          if ! docker image inspect myimage:latest > /dev/null 2>&1; then
            docker build -t myimage:latest -f ./Dockerfile .
          fi

      # Run Docker container in detached mode (background)
      - name: Run Docker container in detached mode
        run: |
          docker run -d --name test-container myimage:latest bash

      # Attach to the running container and run commands interactively (you'll see this in the logs)
      - name: Attach to container and run colcon build interactively
        run: |
          docker attach test-container
          # Once attached, you will be able to run commands interactively in the terminal
          echo "Current directory before colcon build:"
          docker exec test-container pwd
          echo "Listing directory contents:"
          docker exec test-container ls -al
          echo "Sourcing ROS setup files:"
          docker exec test-container bash -c "source /opt/ros/humble/setup.bash && source ~/ros_ws/install/setup.bash"
          echo "Running colcon build:"
          docker exec test-container colcon build

      # Print colcon build result (logs)
      - name: Show colcon build result
        run: |
          docker logs test-container

      # Stop and remove Docker container after the build
      - name: Clean up Docker container
        run: |
          docker stop test-container
          docker rm test-container
