name: Build and Run colcon in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (optional for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build Docker image if it doesn't already exist
      - name: Build Docker image if it doesn't exist
        run: |
          if ! docker image inspect myimage:latest > /dev/null 2>&1; then
            docker build -t myimage:latest -f ./Dockerfile .
          fi

      # Run Docker container from the image and execute colcon build
      - name: Run Docker container and execute colcon build
        run: |
          # Run container with a command to build the ROS workspace
          docker run --name test-container -d myimage:latest bash -c "source /opt/ros/humble/setup.bash && colcon build"

      # Print colcon build result (logs)
      - name: Show colcon build result
        run: |
          docker logs test-container
          
      # Stop and remove Docker container after the build
      - name: Clean up Docker container
        run: |
          docker stop test-container
          docker rm test-container
