# .github/workflows/main.yml
name: Build ROS2 Workspace

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Use custom colcon build action
        uses: ./.github/actions/colcon-build-action  # Reference your custom action in the relative path
        with:
          command: 'colcon build'  # You can modify the command if needed

      - name: Check build status
        run: |
          echo "Build completed successfully!"
