name: Build and Check colcon on Commit to Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (optional for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build Docker image from the custom Dockerfile in the repository
      - name: Build Docker image from custom Dockerfile
        run: |
          docker build -t myimage:latest -f ./Dockerfile .

      # Run Docker container
      - name: Run Docker container
        run: |
          docker run -d --name mycontainer myimage:latest

      # Set up ROS 2 environment in Docker container and run colcon build
      - name: Set up ROS 2 environment in Docker container and run colcon build
        run: |
          docker exec mycontainer bash -c "source /opt/ros/humble/setup.bash && \
          source ~/ros_ws/install/setup.bash && \
          colcon build"

      # Check the result of colcon build and show output
      - name: Show colcon build result
        run: |
          docker exec mycontainer bash -c "source /opt/ros/humble/setup.bash && \
          source ~/ros_ws/install/setup.bash && \
          colcon build && \
          tail -n 20 ~/ros_ws/log/latest_build/colcon_build_output.log"

      # Clean up Docker container after the build
      - name: Clean up Docker container
        run: |
          docker stop mycontainer
          docker rm mycontainer
